name: Publish Python 🐍 distribution 📦 to PyPI and TestPyPI

on: push

jobs:
  build:
    name: Build distribution 📦
    runs-on: ubuntu-latest
    strategy:
        fail-fast: false
        matrix:
          py:
            - "3.12"
            - "3.11"
            - "3.10"
            - "3.9"
  
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.py }}
    - name: setup-chromedriver
      uses: nanasess/setup-chromedriver@v2.2.2
    - name: Install pypa/build
      run: >-
        python3 -m
        pip install
        build
        --user
    - name: Install tox
      run: python -m pip install tox-gh>=1.2
    - name: Setup test suite
      run: tox -vv --notest
    - name: Run test suite
      run: tox --skip-pkg-install
    - name: Build a binary wheel and a source tarball
      run: python3 -m build
    - name: Store the distribution packages
      uses: actions/upload-artifact@v4
      with:
        name: python-package-distributions
        path: dist/

  publish-to-pypi:
    name: >-
      Publish Python 🐍 distribution 📦 to PyPI
    if: startsWith(github.ref, 'refs/tags/')  # only publish to PyPI on tag pushes
    needs:
    - build
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/undetected-browser-tool  # Replace <package-name> with your PyPI project name
    permissions:
      id-token: write  # IMPORTANT: mandatory for trusted publishing

    steps:
    - name: Download all the dists
      uses: actions/download-artifact@v4
      with:
        name: python-package-distributions
        path: dist/
    - name: Publish distribution 📦 to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1